// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx9mOhTST66xrGcP80rr8XLdi3-N3txGs',
    appId: '1:578514078034:web:8916c87f6a2ee4d857928b',
    messagingSenderId: '578514078034',
    projectId: 'field-app-3115d',
    authDomain: 'field-app-3115d.firebaseapp.com',
    storageBucket: 'field-app-3115d.appspot.com',
    measurementId: 'G-HJDG9VYVVB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvhbaP-4ZgayG7Pmrjy9vivt6WqlXdDfQ',
    appId: '1:578514078034:android:64efb56920fe149c57928b',
    messagingSenderId: '578514078034',
    projectId: 'field-app-3115d',
    storageBucket: 'field-app-3115d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSlx8eJYyLlDFYK0kRFI0lQOXaZh4oQcU',
    appId: '1:578514078034:ios:e17a2378c025ee1857928b',
    messagingSenderId: '578514078034',
    projectId: 'field-app-3115d',
    storageBucket: 'field-app-3115d.appspot.com',
    iosBundleId: 'com.example.knowledgeCenterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSlx8eJYyLlDFYK0kRFI0lQOXaZh4oQcU',
    appId: '1:578514078034:ios:cd411a82e621baef57928b',
    messagingSenderId: '578514078034',
    projectId: 'field-app-3115d',
    storageBucket: 'field-app-3115d.appspot.com',
    iosBundleId: 'com.example.knowledgeCenterApp.RunnerTests',
  );
}
